### ISSUE TITLE
Machine-readable requirements

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-standoc#34]
There are two approaches to machine-readable requirements:

1. declarative
2. in-prose (aka textual content tagging).

A declarative requirement is a data structure, where you specify:

* subject: who is the requirement addressed to?
* obligation: is this a "permission", "recommendation", "requirement"?
** MUST/SHALL, SHOULD, or CAN?
* qualitative or quantitative?
** if quantitative, what are the measurement targets?
* object: what is the object requirement?
* verification steps: what steps do we take to verify the requirement has been met?

In text, this may look like:

```
[requirement,type=recommendation,subject=“The user”,obligation=must,object=“be logged in”]
```

or

```
[requirement, type=recommendation]
* The user must be logged in
```

In the ideal world all requirements are stated this way in the XML and also in rendered output (e.g. in a table form).

However, in the real-world many requirements are embedded in content text (the narrative). We don’t have the authority to re-format all of that text into the above format (and the myriad authors probably won’t want to do so either).

So the other approach is through “tagging”, similar to the general approach with TEI. For example, "The user must be logged in” can be represented in text like:

“
[subject]#The user# [obligation]#must# [object]#be logged in#.
"

The difference between these two approaches is both in the input syntax and the output rendering. Their representation in XML however, is identical.

NOTE: In IETF XML they use the <bcp14> tag to tag obligation elements, such as <bcp14>MUST NOT</bcp14>

Hierarchical requirements, multiple requirements should be allowed.

It seems that we can model a requirement in AsciiDoc as a Section, a List or a Paragraph?

**Comment by opoudjis** [comment]
There are two encodings I've already had to do in Metanorma XML for this:

In OGC, tables have been used as a legacy encoding, and we will presumably want to move away from them. OGC require an internal label, which is distinct from an anchor for the text (it is a slash-delimited path):

````
[[recommendation1]]
|===
|Recommendation |/ogc/recommendation/wfs/2 +

If the API definition document uses the OpenAPI Specification 3.0,
the document SHOULD conform to the
<<rc_oas30,OpenAPI Specification 3.0 requirements class>>.
|===
````

For NIST, we used examples, as the most flexible text container. It has been argued that pseudo-code excerpts in NIST also count as requirements, but in fact I have encoded them in Asciidoctor as examples anyway, and rendered them as either examples or figures (that decision is still in flux); in any case, if they truly are requirements, they can still be captured as Asciidoctor examples.

The Asciidoctor examples labelled with the style attributes requirement, permission, recommendation have been differentiated in Metanorma XML as tags with name requirement, permission, recommendation. So I do not use the one tag to represent all three. The obligation is specified in the tag name. (This can be revisited, but I'd rather not, since as assets, requirements, permissions, recommendations in a document are numbered separately; that certainly appears to be the case in NIST.)

So the metadata around the requirement is :

* subject: who is the requirement addressed to?
* obligation: is this a "permission", "recommendation", "requirement"?
* qualitative or quantitative? If quantitative, what are the measurement targets?
* object: what is the object requirement?
* verification steps: what steps do we take to verify the requirement has been met?
* label

Of these, the obligation is captured as the tag name in Metanorma XML, and as the style attribute in Metanorma Asciidoctor markup. The label is a token and the subject is a phrase; both can be entered straightforwardly as named attributes on the requirement in Asciidoctor, as already proposed above.

The object, measurement targets, and verification steps are all potentially discursive text, which may well be rich text (one would assume lists for verification steps for example, and possibly nested lists at that). For that reason, I have changed my mind, and now would advocate markup of spans within the requirement, I would allow the markup to be fairly free, with multiple verification, target and object spans in any order, and permitting text not to belong to any of them:

````
requirement = element requirement { Requirement }
recommendation = element recommendation { Requirement }
permission = element permission { Requirement }

label = element label { xsd:token }
subject = element subject { xsd:NormalizedString }

verification = element verification {
  (paragraph-with-footnote | table | formula | admonition | ol | ul | dl | example | sourcecode | review )*
}

measurementtarget = element measurementtarget {
  (paragraph-with-footnote | table | formula | admonition | ol | ul | dl | example | sourcecode | review )*
}

object = element object {
  (paragraph-with-footnote | table | formula | admonition | ol | ul | dl | example | sourcecode | review )*
}

Requirement = 
  attribute id { xsd:ID },
  label?, subject?, ( verification | object | measurementtarget | paragraph-with-footnote | table | formula | admonition | ol | ul | dl | example | sourcecode | review | requirement | recommendation | permission )* 
````

Asciidoctor permits example embedding, so the requirement for nested requirements can be met.

**Comment by opoudjis** [comment]
I'm creating this in a separate branch of metanorma-standoc, with examples in rspec.

**Comment by opoudjis** [comment]
Implemented, with examples at the end of spec/asciidoctor-standoc/blocks_spec.rb, in branch requirements. @ronaldtse Please review.

**Comment by opoudjis** [comment]
Will also need to realise rendering of requirements in isodoc, once the requirements branch of metanorma-standoc is approved.

**Comment by opoudjis** [comment]
After that, need to add requirements to grammar.

**Comment by opoudjis** [comment]
@ronaldtse, need the Chinese  for Requirement, Recommendation, Permission.

**Comment by opoudjis** [comment]
Requirements will end up in separate UML model and grammar, inherited into Metanorma like biblio.rnc is.

**Comment by ronaldtse** [comment]
Chinese:

* Requirement 要求 （Trad）要求（Simp）
* Recommendation 建議 （Trad）建议（Simp）
* Permission 容許 （Trad） 容許（Simp）

**Comment by opoudjis** [comment]
Isodoc rendering done, UML modelling underway.

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma-requirements-models
